---
title: "TLS_FvFm_methods_exp3"
author: "Pieter Arnold, Rosalie Harris, Sabina Aitken"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

Load in R packages that are required.

```{r}

pacman::p_load(ggplot2, lmerTest, dplyr, tidyr, plotrix, performance, scales, ggpubr)

```

## Load data

```{r}

dat <- read.csv("Data/Exp3_wide.csv")

dat <- unite(dat, Temp_Time, c(Temp, Time))
str(dat)

initial_summary <- dat %>%
  group_by(Species,Temp_Time, Leaf) %>%
  summarise(
    sd = sd(initial, na.rm = TRUE),
    se = std.error(initial, na.rm = TRUE),
    initialmean = mean(initial, na.rm = TRUE))

initial_summary$Species = factor(initial_summary$Species, levels = c("Euc", "Lomandra", "Poplar", "Bean"))
initial_summary$fvfm <- initial_summary$initialmean
initial_summary$Measure <- "Initial"

final_summary <- dat %>%
  group_by(Species,Temp_Time, Leaf) %>%
  summarise(
    sd = sd(final, na.rm = TRUE),
    se = std.error(final, na.rm = TRUE),
   finalmean = mean(final, na.rm = TRUE))

final_summary$fvfm <- final_summary$finalmean
final_summary$Measure <- "Final"
final_summary$Species = factor(final_summary$Species, levels = c("Euc", "Lomandra", "Poplar", "Bean"))

sp_names <- c(`Bean` = "Vicia faba",
              `Euc` = "Eucalyptus pauciflora",
              `Lomandra` = "Lomandra longifolia",
              `Poplar` = "Populus nigra")

combined_data <- bind_rows(
  initial_summary %>% mutate(Measurement = "Initial", value = initialmean, se_val = se),
  final_summary %>% mutate(Measurement = "Final", value = finalmean, se_val = se)
)

combined_data <- combined_data %>%
  mutate(Temp_Time = factor(Temp_Time, 
                            levels = c("30_5", "30_30", "30_120",
                                      "40_5", "40_30", "40_120",
                                      "48_5", "48_30", "48_120"))) %>%
  mutate(Measurement = factor(Measurement, levels = c("Initial", "Final")))

sp_labels <- c(
  "Euc" = "italic(Eucalyptus~pauciflora)",
  "Lomandra" = "italic(Lomandra~longifolia)",
  "Poplar" = "italic(Populus~nigra)",
  "Bean" = "italic(Vicia~faba)"
)

sp_labeller <- function(variable, value) {
  return(sp_labels[value])
}

ggplot(combined_data, aes(x = Temp_Time, y = value, 
                          color = Leaf, shape = Measurement)) +
  geom_pointrange(aes(ymin = value - se_val, ymax = value + se_val), 
                  size = 0.4, alpha = 1, position = position_dodge(width = 0.4)) +
  facet_grid(~Species, labeller = labeller(Species = as_labeller(sp_labels, label_parsed))) +
  scale_color_manual(values = c("Whole" = "#238B45", "Cut" = "#80CDC1")) +
  scale_shape_manual(values = c("Initial" = 16, "Final" = 17)) +
  scale_y_continuous(breaks = seq(0, 0.8, 0.2), limits = c(0, 0.9)) +
  labs(y = bquote(italic(F)[V]/italic(F)[M]), 
       x = bquote(Temperature~(degree*C)~"_"~Duration~(min))) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
    legend.position = "bottom"
  )

# Plot just the final Fv/Fm
final_summary <- final_summary %>%
  mutate(Temp_Time = factor(Temp_Time, 
                            levels = c("30_5", "30_30", "30_120",
                                      "40_5", "40_30", "40_120",
                                      "48_5", "48_30", "48_120"))) 

ggplot(final_summary, aes(x = Temp_Time, y = finalmean, 
                          color = Leaf)) +
  geom_pointrange(aes(ymin = finalmean - se, ymax = finalmean + se), 
                  size = 0.4, alpha = 1, position = position_dodge(width = 0.4)) +
  facet_grid(~Species, labeller = labeller(Species = as_labeller(sp_labels, label_parsed))) +
  scale_color_manual(values = c("Whole" = "#238B45", "Cut" = "#80CDC1")) +
  scale_y_continuous(breaks = seq(0, 0.8, 0.2), limits = c(0, 0.9)) +
  labs(y = bquote(italic(F)[V]/italic(F)[M]), 
       x = bquote(Temperature~(degree*C)~"_"~Duration~(min))) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
    legend.position = "bottom"
  )


ggsave("Plots/Fig_Exp3.pdf", width = 7, height = 3)

```

## Statistical models

```{r}

mod_exp3 <- lmer(fvfm ~ Leaf * Temp_Time * Measurement + (1|Species), data = combined_data)
print(anova(mod_exp3, digits=2))

mod_exp3 <- lm(fvfm ~ Leaf * Temp_Time * Species + Measurement, data = combined_data)
anova(mod_exp3)

mod_exp3_initial_full <- lm(initial ~ Leaf * Temp_Time * Species, data = dat)
anova(mod_exp3_initial_full)

mod_exp3_final_full <- lm(final ~ Leaf * Temp_Time * Species, data = dat)
anova(mod_exp3_final_full)

mod_exp3_initial <- lmer(initial ~ Leaf * Species + (1|Temp_Time), data = dat)
anova(mod_exp3_initial)

mod_exp3_final <- lmer(final ~ Leaf * Species + (1|Temp_Time), data = dat)
anova(mod_exp3_final)

```
